//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SınavOgrenciEFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTLAR
    {
        public int notid { get; set; }
        public Nullable<int> ogrenciid { get; set; }
        public Nullable<int> dersid { get; set; }
        public Nullable<short> sınav1 { get; set; }
        public Nullable<short> sınav2 { get; set; }
        public Nullable<short> sınav3 { get; set; }
        public Nullable<decimal> ortalama { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual TBLDERSLER TBLDERSLER { get; set; }
        public virtual TBLOGRENCI TBLOGRENCI { get; set; }
    }
}
